### ISSUE TITLE
componentWillReceiveProps of the lifted component won't be called

### ISSUE THREAD

**Issue by littlehaker** [jwoudenberg/flyd-lift-react#18]
Consider the render function, `this.state` will always be the same reference, so `componentWillReceiveProps` of `Component` won't be called.

``` javascript
render: function render () {
    var props = this.state;
    return React.createElement(
        Component,
        props
    );
}
```

Perhaps we can use `var props = { ...this.state }` instead.

**Comment by littlehaker** [comment]
Sorry, my fault. It's not the reason why `componentWillReceiveProps` not be called in my senerio, so close it.

**Comment by jwoudenberg** [comment]
Glad you found it!
